language: php

sudo: false

env:
  global:
    - secure: "a2at492H86Eyz8hToIFBUrZ41uuw4th3a01iQCa1trtzytZbpCPRuXejcN4Y7hRUisdvexRzUvwfvMBffZNu9JIyMWtYnGbpfxFVBDp+yL4rlvRMPGCJTf7vsFFuXY+o6EPFhNdpTq1RfqaVtS2Ie2q2OrUL0Kmr4WfM8Nl70nt2Vtm7ZayLGs+K1id47+FBIYZDfWp9XPnMh7uSnklU5Hk5tJkFmtI0C9YDrADK1CrFWRBAsG5Eos8C8qmtNWnCI0prqC4rYdWT61RNED/+wmvQwIV+g2i6sGbTMEobNmYKqYcgPzPQ/qYNxy5jrXwNXg4uAiXbgB1i5ysi+TbIQI+AaoxwjJqaCcGxylP02ZZWkfVzeatgYF1XMSj4ZcXSjYE7GaX6cUiQAm3M1SBskd2Qlg5IKM+fT9eRyFsveqzFzxGrPf6eYrt3jVeWqdbXegYcqfV8/CYVex/oO3qAteyG3Jk1RuOdbk8tot4Akw5jq1C9VBoR//VCCLMHFFLY3+XlPt2lo3OG4uPSkknYyWC5MEs5KJIrTSfa7GhzuvuGnSBJLc8MvljWODMgjRnwaHWM/9CRpD8ayX3nCAvieUDRSUkcP93geDGr+ye8fTLpNa7xO3+xsh/K8vilTkvlysBHmacsA68bfJwuUpFjCIeMtvYO8+kTgZz4YiablcA="
    - secure: "JUg9vF+ofEkz9EPksv6mRJ97KOc6dU66h9Jo0r6c+v9ZG5jcpNJkiXuu7EOQ+E6W7BvCLEqYGW7c245+3+l7djtOZaf/+Xzjav1tKTRlY5nkd94GKEg1/MMRgPaqMc4MeVcYYam9xG5f+WbNokiz7R6M0OSpBIs0t04YnZyg3zJ09Z09Mds5SfKsr0/DTleQGAYTwdxT2ZBByEs2ttXhP5MoiffbLAsGi6XU1CrKzHv0AzBaisAVOk6rS7jsrLhPsNN9ioML33d2JEBVBNox3UU8ynjWX/fmjQLfK8scbFRz0OuyU+OkrArlJkPCeAHzsl9iOvMtxbhZCly4AP7RcosaA3cIa+I0nQss2YBoPNJ0+kyM8lacJSQ1TAx6EI+CzhZBIdfoS4+7I/2zLg7uIcI0mi8CFlaYWZekxZn6b9fBudfemhsvRVg9ZtlfRmCal9etVgdGS1qh+MPE43PjGjqJ3q5Re3BbQzunxGDbrgfV+BgQEoR7/0TG1lLhpYjEdYQIjoC3l0VhIUW8i9q4nb7AHy+gAd234prqHBmnY/UqDKFE9Xc7LIUfs+QuKu60EImoPAntBdioOsFHY0AkM+u+mFbrvgIHUbmPYuq8UGecdOaAm2c+jjoktR4WSNyYIehTIu/vTio2Z/sYVwcumzQle4KpOowkmzvFxldFCCo="

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env: COLLECT_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run
  - bin/phpspec run --format=dot

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$COLLECT_COVERAGE" == "true" ]]; then bin/report-coverage; fi
