language: php

sudo: false

env:
  global:
    - secure: "X/YjjTmVazPmUoD55aVG33tB2lY9wVo8puE2xNwqyBZn5rcjdo4yyea9xXJQoWSyUjU8zXC62BUa46oJiQWJbep2vPpPj+0AIx/Gz4HkZ7l39GdA6+94SY2zy1ru+QfvThoC44yj/pgWTUMNHUceaW+fs8qQwH6FZMvvHQAjbWypB2yr5+ZA7Y73owZAwapuckBR+vyvCUvkLVsKneNCMqJtUWso+N24E4IMYiXpb0c/DQ/YpXzeWInrUxFlIxL9+OJrJ7AsbC2GKKqOimtTgIqBOYSUL4Hj5Kg5yFM1Y8R3BIhtA4d1mwiXOkvtD8sCRIjlllK5D1uRz9q1viUJyBT62Ls9qjDVz8zAGgjqnV4DFpRQDbPzunWkjywkP+L6bqN6nmq1Eagw/lJzafrTqlmiYHaJoyKemjJW4GbW3d10PESLAEyoJ7WueaS3GmmYdqh6ABLSnZ97Rhb/BrKSQi17FVP2slY5iTjgql5xAJlBBMY+YR8WSZWIonmo50z0QdnX/TlNdITfrzW8QyjPpUaBdREd4ZtfAA5yAEdpGTzCNC77r0NZ0a8uenf3d9nFDRCGHzHx2H0IOJ0e59eGWcNJppK7JZOc4LJo8GVra8EjaC3PMyZqrwK0FTBzMn8GuCfxlR5nealFkI6364m7EMSIPfHblxx5oy511fMo4tA="
    - secure: "JUg9vF+ofEkz9EPksv6mRJ97KOc6dU66h9Jo0r6c+v9ZG5jcpNJkiXuu7EOQ+E6W7BvCLEqYGW7c245+3+l7djtOZaf/+Xzjav1tKTRlY5nkd94GKEg1/MMRgPaqMc4MeVcYYam9xG5f+WbNokiz7R6M0OSpBIs0t04YnZyg3zJ09Z09Mds5SfKsr0/DTleQGAYTwdxT2ZBByEs2ttXhP5MoiffbLAsGi6XU1CrKzHv0AzBaisAVOk6rS7jsrLhPsNN9ioML33d2JEBVBNox3UU8ynjWX/fmjQLfK8scbFRz0OuyU+OkrArlJkPCeAHzsl9iOvMtxbhZCly4AP7RcosaA3cIa+I0nQss2YBoPNJ0+kyM8lacJSQ1TAx6EI+CzhZBIdfoS4+7I/2zLg7uIcI0mi8CFlaYWZekxZn6b9fBudfemhsvRVg9ZtlfRmCal9etVgdGS1qh+MPE43PjGjqJ3q5Re3BbQzunxGDbrgfV+BgQEoR7/0TG1lLhpYjEdYQIjoC3l0VhIUW8i9q4nb7AHy+gAd234prqHBmnY/UqDKFE9Xc7LIUfs+QuKu60EImoPAntBdioOsFHY0AkM+u+mFbrvgIHUbmPYuq8UGecdOaAm2c+jjoktR4WSNyYIehTIu/vTio2Z/sYVwcumzQle4KpOowkmzvFxldFCCo="

matrix:
  include:
    - php: 5.6
      env: COLLECT_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run
  - bin/phpspec run --format=dot

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$COLLECT_COVERAGE" == "true" ]]; then bin/test-reporter; fi
